const SKILLS = {
	HTML: 'icon-[vscode-icons--file-type-html]',
	CSS: 'icon-[vscode-icons--file-type-css]',
	JavaScript: 'icon-[vscode-icons--file-type-js-official]',
	TypeScript: 'icon-[vscode-icons--file-type-typescript-official]',
	React: 'icon-[vscode-icons--file-type-reactjs]',
	Go: 'icon-[vscode-icons--file-type-go]',
	PHP: 'icon-[vscode-icons--file-type-php]',
	PostgreSQL: 'icon-[vscode-icons--file-type-pgsql]',
	MySQL: 'icon-[vscode-icons--file-type-mysql]',
	SAP: 'icon-[simple-icons--sap]',
	Vue: 'icon-[vscode-icons--file-type-vue]',
	'Express.js': 'icon-[simple-icons--express]',
	'Next.js': 'icon-[vscode-icons--file-type-next]',
	jQuery: 'icon-[simple-icons--jquery]',
	Drupal: 'icon-[logos--drupal-icon]',
	Linux: 'icon-[logos--linux-tux]',
	'Material-UI': 'icon-[logos--material-ui]',
	'Charka-UI': 'icon-[simple-icons--chakraui]',
	Sass: 'icon-[vscode-icons--file-type-sass]',
	Redux: 'icon-[logos--redux]',
	'Node.js': 'icon-[vscode-icons--file-type-node]',
	Git: 'icon-[logos--git-icon]',
	GitHub: 'icon-[simple-icons--github]',
	GitLab: 'icon-[logos--gitlab]',
	Bash: 'icon-[logos--bash-icon]',
	Docker: 'icon-[logos--docker-icon]',
	'Ant-Design': 'icon-[logos--ant-design]',
	Bootstrap: 'icon-[logos--bootstrap]',
	Astro: 'icon-[vscode-icons--file-type-astro]',
	TailwindCSS: 'icon-[logos--tailwindcss-icon]',
	Iconify: 'icon-[simple-icons--iconify]',
	Vercel: 'icon-[simple-icons--vercel]',
	Tauri: 'icon-[logos--tauri]',
	Svelte: 'icon-[logos--svelte-icon]',
	Python: 'icon-[logos--python]',
	Prisma: 'icon-[simple-icons--prisma]',
	'Swiper.js': 'icon-[simple-icons--swiper]',
	'Alpine.js': 'icon-[logos--alpinejs-icon]',
	Haskell: 'icon-[logos--haskell-icon]',
	Racket: 'icon-[vscode-icons--file-type-racket]',
	MongoDB: 'icon-[vscode-icons--file-type-mongo]',
	'Styled Components': 'icon-[vscode-icons--file-type-styled]',
	Dart: 'icon-[logos--dart]',
	Flutter: 'icon-[logos--flutter]',
	Framer: 'icon-[simple-icons--framer]',
	Bun: 'icon-[logos--bun]',
} as const

export type Skill = keyof typeof SKILLS

export const skill = (skill: Skill) => ({ name: skill, icon: SKILLS[skill] })
